parameters:
    database_driver:   pdo_mysql
    database_host:     db463938985.db.1and1.com
    database_port:     3306
    database_name:     db463938985
    database_user:     dbo463938985
    database_password: Ae6wu323MH

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
