parameters:
#    forthicime_admin.example.class: Forthicime\AdminBundle\Example

services:
#    forthicime_admin.example:
#        class: %forthicime_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
