<?php

namespace Forthicime\MedecinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoginHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginHistoryRepository extends EntityRepository
{
}
