<?php

namespace Forthicime\DossierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccessHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessHistoryRepository extends EntityRepository
{
	public function getLatestRead($medecin)
	{
		return $this->createQueryBuilder("a")
             ->select("d.id, d.libelle, c.nom, c.prenom, a.access, d.created, m.nom as nomMedecin")   
             ->innerJoin("a.dossier", "d")
             ->innerJoin("d.client", "c")                                
             ->innerJoin("d.medecin", "m") 
             ->where("d.medecin = :medecin")             
             ->setParameter('medecin', $medecin)    
             ->setMaxResults(10)       
             ->orderBy('a.access', 'DESC')                     
             ->getQuery()
             ->getResult();	


            // $ql = $this->createQueryBuilder("aa");
            // $access = $ql->select("ad")
            //              ->from("Forthicime\DossierBundle\Entity\AccessHistory", "ad")
            //              ->where("ad.medecin = :medecin")
            //              ->setParameter('medecin', $medecin)    
            //              ->orderBy('ad.access', 'DESC')
            //              ->setMaxResults(10)
            //              ->getDQL();

            // $qle = $this->createQueryBuilder("dd");
            // $dossiers = $qle->select("do, c")                                   
            //                 ->from("Forthicime\DossierBundle\Entity\Dossier", "do")
            //                 ->where($qle->expr()->in('do.id', $access))
            //                 ->leftJoin("do.client", "c")
            //                 ->getQuery()
            //                 ->getResult();

            // return $dossiers;
	}

      public function getLatestReadFromAll()
      {
            return $this->createQueryBuilder("a")
             ->select("d.id, d.libelle, c.nom, c.prenom, a.access, d.created, m.nom as nomMedecin")   
             ->innerJoin("a.dossier", "d")
             ->innerJoin("d.client", "c")                 
             ->innerJoin("d.medecin", "m")             
             ->setMaxResults(10)       
             ->orderBy('a.access', 'DESC')                     
             ->getQuery()
             ->getResult();   
      }


}
