<?php

namespace Forthicime\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SynchronizationLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SynchronizationLineRepository extends EntityRepository
{
}
