<?php

namespace Forthicime\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SynchronizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SynchronizationRepository extends EntityRepository
{
}
